//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaFramework_ResourceLoadTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(LuaFramework.ResourceLoadType));
		L.RegVar("Default", get_Default, null);
		L.RegVar("Persistent", get_Persistent, null);
		L.RegVar("Cache", get_Cache, null);
		L.RegVar("UnLoad", get_UnLoad, null);
		L.RegVar("Immediate", get_Immediate, null);
		L.RegVar("LoadBundleFromFile", get_LoadBundleFromFile, null);
		L.RegVar("LoadBundleFromWWW", get_LoadBundleFromWWW, null);
		L.RegVar("ReturnAssetBundle", get_ReturnAssetBundle, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<LuaFramework.ResourceLoadType>.Check = CheckType;
		StackTraits<LuaFramework.ResourceLoadType>.Push = Push;
	}

	static void Push(IntPtr L, LuaFramework.ResourceLoadType arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(LuaFramework.ResourceLoadType), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Default(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.ResourceLoadType.Default);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Persistent(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.ResourceLoadType.Persistent);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Cache(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.ResourceLoadType.Cache);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UnLoad(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.ResourceLoadType.UnLoad);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Immediate(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.ResourceLoadType.Immediate);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LoadBundleFromFile(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.ResourceLoadType.LoadBundleFromFile);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LoadBundleFromWWW(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.ResourceLoadType.LoadBundleFromWWW);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ReturnAssetBundle(IntPtr L)
	{
		ToLua.Push(L, LuaFramework.ResourceLoadType.ReturnAssetBundle);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		LuaFramework.ResourceLoadType o = (LuaFramework.ResourceLoadType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

